// src/styles.js
// Shared inline styles — move to CSS modules or Tailwind in production

export const styles = {
  pageCenter: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#f8fafc",
    padding: "2rem",
  },
  card: {
    background: "#ffffff",
    borderRadius: 16,
    border: "1px solid #e2e8f0",
    padding: "2rem",
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },
  cardHeader: {
    textAlign: "center",
    marginBottom: "1.5rem",
  },
  lockIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  h1: {
    fontSize: 22,
    fontWeight: 600,
    margin: "0 0 4px",
    color: "#0f172a",
  },
  muted: {
    fontSize: 13,
    color: "#64748b",
    margin: 0,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginBottom: "1.5rem",
  },
  label: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
    fontSize: 14,
    fontWeight: 500,
    color: "#334155",
  },
  input: {
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid #cbd5e1",
    fontSize: 14,
    outline: "none",
    transition: "border-color 0.15s",
  },
  errorBanner: {
    background: "#fef2f2",
    color: "#b91c1c",
    border: "1px solid #fecaca",
    borderRadius: 8,
    padding: "10px 12px",
    fontSize: 13,
  },
  btnPrimary: {
    background: "#2563eb",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "11px 0",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    width: "100%",
  },
  btnDanger: {
    background: "#fff",
    color: "#dc2626",
    border: "1px solid #fca5a5",
    borderRadius: 8,
    padding: "10px 0",
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    width: "100%",
    marginTop: "1rem",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginBottom: "1.5rem",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "#dbeafe",
    color: "#1d4ed8",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    fontWeight: 700,
    flexShrink: 0,
  },
  divider: {
    borderTop: "1px solid #f1f5f9",
    margin: "1.25rem 0",
  },
  table: {
    width: "100%",
    fontSize: 13,
    borderCollapse: "collapse",
  },
  tdLabel: {
    color: "#64748b",
    padding: "6px 0",
    width: 90,
    verticalAlign: "top",
  },
  tdValue: {
    color: "#0f172a",
    padding: "6px 0",
    fontWeight: 500,
  },
  badge: {
    display: "inline-block",
    background: "#ede9fe",
    color: "#5b21b6",
    borderRadius: 6,
    padding: "2px 8px",
    fontSize: 12,
    fontWeight: 600,
    marginRight: 4,
  },
  securityPanel: {
    background: "#f0fdf4",
    borderRadius: 10,
    border: "1px solid #bbf7d0",
    padding: "0.875rem 1rem",
  },
  securityList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
    fontSize: 13,
    color: "#166534",
    lineHeight: 1.9,
  },
  loadingWrapper: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  spinner: {
    width: 28,
    height: 28,
    border: "3px solid #e2e8f0",
    borderTop: "3px solid #2563eb",
    borderRadius: "50%",
    animation: "spin 0.7s linear infinite",
  },
};